### ISSUE TITLE
Provide apiary.io fetch & publishing

### ISSUE THREAD

**Issue by liguori** [XVincentX/vscode-apielements#22]
It would be a nice extension feature to implement a new functionality for:
1. Connect to an existent apiary.io account
2. Fetch and explore online api
3. Publish on apiary.io api changes

**Comment by XVincentX** [comment]
Hello, and thanks a lot for the getting in touch.

Actually Apiary provides some tools to do the job here.

In particular, you can use [apiary client](http://client.apiary.io) to fetch and publish your API documents. If those are linked with Github, the integration will still happen.

Moreover, if you're using [Github integration](https://help.apiary.io/tools/github-integration/), you can use the normal Github flow to make sure everything stays up to date (and VSCode has a great integration for that)

Nevertheless, I still think not everybody is using GitHub, as well less you leave your editor, more happy you are.

This is something I'd might be interested working on, but not in the near future. Swagger support is not more important.

Would you be interested to submit a PR, eventually?

**Comment by XVincentX** [comment]
@liguori #23

**Comment by XVincentX** [comment]
@liguori This has been implemented and published in 0.2.0

**Comment by liguori** [comment]
I am satisfied about this implementation. 
It's a very good work and it functions very well

Thank!

P.S: Mi puzzano le palle.

**Comment by XVincentX** [comment]
I totally agree with the PS.
