### ISSUE TITLE
editor.adjustOptions should insert spaces to avoid Drafter errors

### ISSUE THREAD

**Issue by PiMaker** [XVincentX/vscode-apielements#33]
Having tabs in a .apib file leads to nasty Drafter errors, having to change it manually every time is annoying. I would suggest either defaulting the `editor.adjustOptions` setting to false or changing the adjustment to include `insertSpaces = true` instead of false as it is right now.

**Comment by XVincentX** [comment]
Hey @PiMaker,
thanks a lot for filing the issue.

You're totally right - it's a bug.

I'll fix this thing as soon as possible and publish it!

**Comment by XVincentX** [comment]
I've just committed https://github.com/XVincentX/vscode-apielements/pull/24/commits/6a97fac255d44150f610b954fb56f3ba6f977250

It will land together with Swagger support which hopefully shouldn't be that far away.
Thanks again!

**Comment by PiMaker** [comment]
Thank you! For now I set adjustOptions to false, but it's good to know I can reenable it on the next update :+1:

**Comment by XVincentX** [comment]
I have just published version 0.3.0 which should fix the issue. I would really love if you could have a look into and let me know if it now makes sense to you!

@PiMaker
