### ISSUE TITLE
Implement Browse to API Command

### ISSUE THREAD

**Issue by XVincentX** [XVincentX/vscode-apielements#38]
It might be handy to have a command to browse the current API based on the name or selecting one if necessary.

**Comment by jsynowiec** [comment]
Does this includes opening a new browser window with the documentation section of Apiary project?

**Comment by XVincentX** [comment]
@jsynowiec 

I haven't finalised it yet, but this would be my idea:

![sep-01-2016 11-14-04](https://cloud.githubusercontent.com/assets/1416224/18162158/630d8d9c-7035-11e6-8a0d-1a9f416b3101.gif)

Thoughts?
