### ISSUE TITLE
[fury] base type 'InvalidCredentialsError' is not defined in the document

### ISSUE THREAD

**Issue by basickarl** [XVincentX/vscode-apielements#68]
I'm getting the error: `[fury] base type 'InvalidCredentialsError' is not defined in the document.`

I'm including the `InvalidCredentialsError` via: `:[Errors](resources/errors.apib)`. That file contains all the error types. I'm including all of these documents via the start apib file (blueprint.apib).

I'm guessing the plugin isn't checking if includes are used in the main file?

**Comment by basickarl** [comment]
It seemed to fix itself when I started to add more text underneath it.

If you end the file with the following:

```
    + Attributes (object)
        + errors (array[InvalidCredentialsError])
```

It will complain as stated in my original post.

**Comment by XVincentX** [comment]
I think this is probably a parser problem not related to the extension itself.
Would it be possible to share the API Blueprint here (or a reproducible example)?

**Comment by basickarl** [comment]
Hi, here is the code I'm using, I've put in the arrow to show where I'm getting the error:

```
# Group User

## User [/{username}]

+ Parameters
    + username (string) - User.

### User [PUT]
Updates user.

+ Request Update user

    + Headers

            Content-Type: application/vnd.api+json

    + Attributes (User)

+ Response 200 (application/vnd.api+json)

    Request.

    + Attributes (object)
        + success: `true` (string) true

+ Response 401 (application/vnd.api+json)

    Response.

    + Attributes (object)
        + errors (array[Incorrect Credentials]) // <--- here is the error line!

# Data Structures

## User (object)

+ type: user (string)
+ attributes (object)
    + id: 1 (number) - Test id.
```

The following however works (the error has moved now).

```
# Group User

## User [/{username}]

+ Parameters
    + username (string) - User.

### User [PUT]
Updates user.

+ Request Update user

    + Headers

            Content-Type: application/vnd.api+json

    + Attributes (User)

+ Response 200 (application/vnd.api+json)

    Request.

    + Attributes (object)
        + success: `true` (string) true

+ Response 401 (application/vnd.api+json)

    Response.

    + Attributes (object)
        + errors (array[Incorrect Credentials]) // <--- the error has been removed here now that i've added more code under (does not show up)

+ Response 402 (application/vnd.api+json)

    Received on invalid/unauthorized JWT token.

    + Attributes (object)
        + errors (array[Incorrect Credentials]) // <--- the error is here now!

# Data Structures

## User (object)

+ type: user (string)
+ attributes (object)
    + id: 1 (number) - Test id.
```

**Comment by XVincentX** [comment]
Thanks a lot - I'll look into!

**Comment by pksunkara** [comment]
This is parser related but it is expected. Since you don't have any data structure named `Incorrect Credentials` parser will produce an error.

**Comment by XVincentX** [comment]
@basickarl Does that answer your question?
If not, you might want to ask more in [drafter](https://github.com/apiaryio/drafter) repository

**Comment by XVincentX** [comment]
Feel free to reopen if you need further clarifications.
