### ISSUE TITLE
Consider switching language ids to lowercase w/o whitespaces

### ISSUE THREAD

**Issue by JimiC** [XVincentX/vscode-apielements#69]
Current `language id` convention is to use lowercase naming.

Currently the usage of `API Blueprint` as `lanuage id` is causing issues with icon associations via `language ids`.

Consider switching:
`API Blueprint` -> `apiblueprint`
`Swagger` -> `swagger`
`MSON` -> `mson`

**Comment by XVincentX** [comment]
Hmm, that seems to be a valid point but - I think I do not get the icon association issue.
Would you mind elaborate more on that?

**Comment by JimiC** [comment]
In case you don't know `vscode` supports icon themes for the explorer. We at `vscode-icons` have created such an extension.
`vscode` associates an icon to a file via the following criteria:
 - filename
 - filename extension
 - language id (either via internal or external extension, such like yours)

We support a majority of files via the `language id` association, including `API Blueprint`.

Now, the mechanism that determines the `language id` doesn't play well when there are whitespaces in the `language id` name. Thus `vscode` fails to correctly associate files to the `language id`, with the effect that the icon doesn't get shown.

The problem only occurs with the `API Blueprint`, but while we are at it I figured I propose to follow the naming convention. Furthermore, `vscode` supports `aliases` property for each `languages` object, which I noticed you don't use. You may want to check to [API docs](https://code.visualstudio.com/docs/customization/colorizer#_add-to-your-language-support-extension) on that.

Hoping that helped.

**Comment by XVincentX** [comment]
Thanks a lot for the detailed explanation. I'm going to handle this as soon as possible.

**Comment by XVincentX** [comment]
@JimiC I've prepared #72 which should do exactly what you've been asking for. Would you mind having a quick look to it? Thanks!

**Comment by XVincentX** [comment]
@JimiC Done and released. Could you verify if that's working correctly now?

**Comment by JimiC** [comment]
Sure. As soon as I get on my workstation.

**Comment by JimiC** [comment]
![image](https://cloud.githubusercontent.com/assets/1716442/24839969/d6885236-1d6c-11e7-9efc-4af60b9637bb.png)
Confirming it works (as soon as we make the necessary changes too).
Note: We don't have an icon for `MSON` yet.

**Comment by XVincentX** [comment]
@JimiC Thanks!

We (Apiary) do not have an official icon for that - I guess you could use the same as apib files.

**Comment by JimiC** [comment]
I was thinking something more in the line of combining `Markdown` and `json` icons. Something like `json-ld` ![json-ld](http://json-ld.org/images/json-ld-data.png).

**Comment by XVincentX** [comment]
@JimiC Let me ask in the company - probably we might come up with something.

**Comment by JimiC** [comment]
That would be awesome. Make sure to include also an SVG version of the icon.
