### ISSUE TITLE
API content is copied into clipboard incorrectly while being folded

### ISSUE THREAD

**Issue by dmrzn** [XVincentX/vscode-apielements#70]
**Steps to recreate the issue:**
1. Add some API text, having regions that can be folded (e.g. an example from http://editor.swagger.io)
2. Fold all regions
3. Select the whole content (Ctrl+A)
4. Copy the content to clipboard (Ctrl+C)
5. Paste to any text editor

**Actual Result:**
The content of last top-level folded region is not copied 

**Expected Result:**
All folded regions should be copied

**Comment by XVincentX** [comment]
Thanks a lot for the bug report - I am going to look into this as soon as possible - although I'm not entirely sure if it's a bug in the extension itself or in Visual Studio Code. I'll keep you posted!

**Comment by XVincentX** [comment]
@dmrzn I haven't been able to reproduce the issue. I've copy pasted the document from VSCode to Sublime and it worked correctly. I am using VSCode 1.11.

Would you mind try this thing again (making sure to update VSCode)?
Feel free to re open the issue if that's still happening.
