### ISSUE TITLE
Tests, ever heard about them?

### ISSUE THREAD

**Issue by XVincentX** [XVincentX/vscode-apielements#8]
It would be great to test what I did so far.

This, of course, won't happen. However, this issue will remember me time after time how sucker I am.

**Comment by XVincentX** [comment]
Contributions welcomed, of course.

**Comment by XVincentX** [comment]
Ahahaha - you know it's not going to happen.

**Comment by houd1ni** [comment]
@XVincentX  You closed it to stop reminding you how sucker you are, you know? You humbled.

**Comment by XVincentX** [comment]
Hey,

kind of. I’m not hiding my failure here. :)

Testing was something that I wanted to do with the extension, I had big plans for it in general — but you can clearly see it didn’t happen and in general the whole extension is not actively developed anymore. I thought it would have been a cool project, but at the end I haven’t been able to grab a decent amount of users to justify my commitment and even the company I was working for (Apiary) which was benefitting from this — didn’t seem to appreciate the project.

I moved my interests elsewhere — and I write tests there, I swear. :) https://github.com/expressgateway/express-gateway

V.

**Comment by houd1ni** [comment]
@XVincentX  Look -- real tests there! Like it.
