### ISSUE TITLE
Error when trying to run client

### ISSUE THREAD

**Issue by keypunch** [XVincentX/vscode-apielements#80]
I've **tried** to follow your instructions exactly.

I downloaded the whole library, and executed the command `npm i` in both **server** and **client** folders.  
I get this warning:

> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

I then opened both **server** and **client** directories as a base path with `code .` (actually open.sh works nicely as well on git-bash).

Now I have 2 instances of vs code open. In the **server** instance I ran the task _Build_ - works great, it's watching.  

In the **client** I don't see any task named _Launch_, so I also run the task _Build_. It finishes without error and creates directory **/client/out**, and **/client/server**. I hit `f5` to enter debug (which should run launch.json right?). Here's where I get this error:

> Attribute 'outDir' does not exist ('d:\projects\vscode-apielements-master\client/out/src').  

I check and yes in fact there is no directory called **/client/out/src/**  

It seems to me like the client is not building correctly. I'm still relatively new to vs code, so I know it's probably just me doing something wrong. Can you spot what I missed?

> Windows 10
VS Code 1.13.1
Api Elements v0.6.7 (from Visual Studio Marketplace)
Node 7.4.0
NPM 5.0.3

**Comment by XVincentX** [comment]
Hey - it's great that you want to hack the extension!

To answer your questions:

You can definitely ignore the warnings - these are just because you're using NPM5 while the extension has been created and updated, so far, with version 4. I plan to update it soon, but it should work anyway.

The procedure to init the extension is correct - and it should work. I think the thing is the task does not create the directory - if it does not exist.

Could you try to post a screenshot?

**Comment by keypunch** [comment]
Thanks for your response. As I said before I'm relatively new to VS Code, and have been deluged in nodejs libraries lately. I assumed I had to do those steps just to make the extension work!   
I just realized yesterday - It's an **_extension_** not a library!  
_*facepalm_

On a positive note, the syntax highlighting looks great!

**Comment by XVincentX** [comment]
All good sir - if you just want to use the extension, you can simply install it directly from the extension store.
