### ISSUE TITLE
why use make the .apib with LF as line ending?

### ISSUE THREAD

**Issue by shangxinbo** [XVincentX/vscode-apielements#81]
I wonder why api blueprint use LF as line ending. I read this issue #18 ,but I can't find the official website description about the line ending.
Is it your own idea or the official is requird. can you give me the link of the doc about that?
I am very difficult to understand this.

**Comment by XVincentX** [comment]
Hey,
this is not my choice but rather something in the official specifications.

I can't find the link right now, but you can notice it by yourself switching the line ending style as CRLF in Visual Studio Code: the parser will return an error (and you'll see it from Visual Studio Code).

Let me know if this answer your question or you need further clarifications.

**Comment by XVincentX** [comment]
@shangxinbo https://github.com/apiaryio/snowcrash/issues/29

**Comment by shangxinbo** [comment]
@XVincentX  Thanks to explain to me . In fact, I know how to change the ending style in VS Code. But when I change it to CRLF, it throw error to me. So I mean this plugin maybe force me to use LF as line ending,that makes me sick.
